openapi: 3.0.0
info:
  title: Sample API
  version: 0.0.1
servers:
  - url: http://localhost:8080/api
    description: Sample Host
tags:
  - name: Sample
paths:
  /urlmap:
    get:
      tags: [ "Sample" ]
      operationId: urlmap
      responses:
        '200':
          description: Sample
  /getTest:
    get:
      tags: [ "Sample" ]
      summary: Get test.
      description: Get test.
      operationId: getTest
      parameters:
        - in: query
          name: name
          schema:
            type: string
      responses:
        '200':
          description: Sample
  /signup:
    post:
      tags: [ "login" ]
      summary: signup.
      description: signup
      operationId: signup
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: login
  /login:
    post: 
      tags: ["login"]
      summary: login
      operationId: login
      requestBody:
        content:  
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: login